Various overall changes
mybb/blog.mybb.com-drafts pull request #3
Opened 2017-10-19 18:39 UTC by Eric-Jackson

Added some lists, more links, cleaned up some of the copy, added a header, etc.

2017-10-19 19:00 UTC, Ben-MyBB approved these changes
Looks good to me.

2017-10-19 21:07 UTC, euantorano requested changes
Some minor changes and comments.

2017-10-19 21:07 UTC, euantorano commented on october-2017/17.md
> +Our blog will be getting some love as well. We're now creating our blog posts via a repository on GitHub, so you can help! (Or just get a sneak peak at what the next blog will be about) If you have a
The bracketed section feels like it should either be before the `!` or have a closing `.`. Not a grammar expert though 😉

2017-10-19 21:07 UTC, euantorano commented on october-2017/17.md
>  [![New MyBB responsive design](../resources/visit-thread-white.svg)](https://community.mybb.com/thread-213603-post-1286609.html#pid1286609)
Maybe also include a link to the `wip.mybb.com` repository?

2017-10-19 21:07 UTC, euantorano commented on october-2017/17.md
> +You may or may not know this, but we keep the community forum as vanilla as possible so users can get a feel for what MyBB is, right out of the box. Unfortunately this limits some decisions we make w
`allowing you as users to browse a clean installation of MyBB easily,` - change the `,` to `.`.

> We are in the process of setting up a new demo system to solve both of these issues, allowing you as users to create and play with a clean installation of MyBB easily. Obviously these demo installs will be lacking a couple of features that a full blown install contains, such as the ability to install custom themes and plugins - this is purely a security precaution.
>
> Providing a clean demo system for users also opens up the possibility for more changes to be made to the official community forum - such as updating the styling to fit in with the rest of the website - in the future.
>
> You can expect work to begin on this project after the new website has launched. Stay tuned for further updates!

2017-10-19 21:07 UTC, euantorano commented on october-2017/17.md
> +It's no secret that getting a modification approved on the MyBB website can be a slow process. The main offender for this is our willingness to make sure submissions are safe and of good quality, whi
> The main offender for this is our mission to ensure that all submissions are safe and of good quality

2017-10-19 21:07 UTC, euantorano commented on october-2017/17.md
> +To speed up your addon submissions, we're going to be easing our policy for allowing submissions. Modifications will be placed into their own category when they're quickly submitted, listing them as
> Modifications will be placed into their own publicly viewable category when they're quickly submitted

(probably best to make it clear)

2017-10-19 21:07 UTC, euantorano commented on october-2017/17.md
> +We are also taking a look into our support of paid modifications. In the past, these have been banned from being posted anywhere on the forum. Paid authors create some great things, so we'd like to e
> We're also considering the possibility of adding thread prefixes to the Requests/Services/Jobs forum in an effort to make clear the kinds of services on offer. If you have any suggestions regarding prefixes you think could aid in the usability of this forum, we're all ears!

2017-10-19 21:07 UTC, euantorano commented on october-2017/17.md
> +We have not decided on any specifics, but have discussed some of the following options:
> We have not decided upon any specifics regarding possible enhancements for the MyBB 1.x series, though some of the following possibilities have been discussed:
> 
> - Using the Twig templating engine to provide an improved templating experience, benefiting theme authors, plugin authors and the core.
> - Implementing support for the SASS styling system, allowing the use of variables and functions when crafting themes.
> - Providing a brand new response default theme with full mobile support for the modern web.
> - Many more user experience improvements, such as implementing common plugins into the core software.

2017-10-19 21:10 UTC, dvz commented on october-2017/17.md
>  [![New MyBB responsive design](../resources/visit-thread-white.svg)](https://community.mybb.com/thread-213603-post-1286609.html#pid1286609)
If it's going to be up in a matter of days, we could leave it off

2017-10-19 21:12 UTC, dvz commented on october-2017/17.md
> +Our blog will be getting some love as well. We're now creating our blog posts via a repository on GitHub, so you can help! (Or just get a sneak peak at what the next blog will be about) If you have a
The former, since we're using BE across the project

2017-10-19 21:16 UTC, Eric-Jackson commented on october-2017/17.md
>  [![New MyBB responsive design](../resources/visit-thread-white.svg)](https://community.mybb.com/thread-213603-post-1286609.html#pid1286609)
It certainly won't be up in days, though the base layout should be ready to start applying to other pages by then. I'll add a link in for that.

2017-10-20 14:13 UTC, euantorano commented on october-2017/17.md
> +We have not decided on any specifics, but have discussed some of the following options:
This comment still seems to stand @Eric-Jackson - not sure why it shows as outdated...

2017-10-22 15:52 UTC, merged